language:
  - cpp

cache:
  ccache: true
  directories:
    - $HOME/downloads

env:
  global:
    - CONFIGURATION=Release
    - PYTHON_VERSION=3.6

matrix:
  include:
    - os: linux
    - os: osx


before_install:

  # Travis machines have 2 cores
  - JOBS=2

  # Handle everything using conda
  - git clone https://github.com/astropy/ci-helpers.git;
  - source ci-helpers/travis/setup_conda.sh;
  - conda install cmake hdf5


script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo $LD_LIBRARY_PATH; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then echo $DYLD_LIBRARY_PATH; fi
  - echo "cmake .. ${CMAKE_OPTIONS}"
  - cmake .. ${CMAKE_OPTIONS}
  - cmake --build .
  # - ctest -v .

after_success:

notifications:
  email: false
